### ISSUE TITLE
Keys not visible in etcd backend?

### ISSUE THREAD

**Issue by wrouesnel** [coreos/zetcd#22]
This may be me not understanding a feature, but I can't see a good reason why not - when testing zetcd against an etcd cluster, although `zkctl` lets me see the keys I've created in the Zookeeper side, I do not see any representation of those keys appearing as listable items in etcd, even though it seems like they should appear under `/zk/*`

**Comment by heyitsanthony** [comment]
How are you accessing the keys?  `ETCDCTL_API=3 ./bin/etcdctl -w json get  --prefix /zk` works for me.

**Comment by wrouesnel** [comment]
Ah, that would explain it. Closing this!
