### ISSUE TITLE
sanitize inputs like zookeeper

### ISSUE THREAD

**Issue by heyitsanthony** [coreos/zetcd#28]
Right now zetcd cleans up the key path before doing anything with it. Zookeeper will just reject it.

cf. https://zookeeper.apache.org/doc/r3.1.2/zookeeperProgrammers.html#ch_zkDataModel

**Comment by xiang90** [comment]
@wrouesnel Do you want to help on this one?

**Comment by wrouesnel** [comment]
Already converted the algorithm. I just need to pin down what state the zxid would be in an error response.

I'll amend the Mesos PR when it's ready since it functionally solves the same problem.
