### ISSUE TITLE
docker image

### ISSUE THREAD

**Issue by heyitsanthony** [coreos/zetcd#50]
docker image for pulling zetcd

**Comment by hunter** [comment]
We built one quickly for testing (zetd/zkctl in a scratch image) if anyone is will to take the risk with an unknown image - quay.io/acaleph/zetcd

I'll raise a PR Dockerfile if I get the time to extract from our build tools

**Comment by xiang90** [comment]
> I'll raise a PR Dockerfile if I get the time to extract from our build tools

it would be great!
