### ISSUE TITLE
ZNode metadata in etcd: physical representation and documentation

### ISSUE THREAD

**Issue by shurup** [coreos/zetcd#52]
In [zetcd introduction](https://coreos.com/blog/introducing-zetcd), there is a [nice illustration](https://coreos.com/sites/default/files/inline-images/organization-of-a-zookeeper-key-hierarchy-in-etcd_0.png) how ZNode metadata is stored in etcd. However, I can't see the same after these simple steps:
```
$ ./go/bin/zkctl watch / &
$ ./go/bin/zkctl create /abc "test"
$ ./go/bin/zkctl create /abc test
2017/05/23 22:36:17 Connected to 127.0.0.1:2181
2017/05/23 22:36:17 Authenticated: id=7587822333160445584, timeout=1000
$ export ETCDCTL_API=3
$ ./go/bin/etcdctl get --prefix /zk
/zk//abc
test
/zk//abc

/zk//

/zk//abc

/zk//abc
�ޗ�׌�
/zk//abc
�ޗ�׌�
/zk//abc
������-��ACL��PermsScheme
                         ID
                           ��>worldanyone
/zk//abc

/zk/e
1
$ 
```
A lot of «/zk//abc» are displayed instead of /zk/key/…, /zk/acl/…, etc I've been expecting (according to the illustration and its description). Am I doing something wrong or this documentation is somehow misleading?

**Comment by heyitsanthony** [comment]
@shuruup build with `-tags path_debug` for human-readable paths

**Comment by shurup** [comment]
Oh, sorry, but after rebuilding everything with `-tags path_debug`, I'm getting "node does not exist":
```
$ ./go/bin/zkctl watch / 
watch dir /
2017/05/24 00:04:25 Connected to 127.0.0.1:2181
2017/05/24 00:04:25 Authenticated: id=7587822335324791310, timeout=1000
zk: node does not exist
$ ./go/bin/zkctl create /abc test
2017/05/24 00:05:18 Connected to 127.0.0.1:2181
2017/05/24 00:05:18 Authenticated: id=7587822335324791315, timeout=1000
zk: node does not exist

```
I've also tried to "empty" everything with `etcdctl del --prefix /zk` but it didn't help. I also recall having /zk/e→1 in etcd (don't actually know what it is :-)) but adding it doesn't change anything as well. What is the best way to start everything from the scratch?

**Comment by shurup** [comment]
Thank you! Now everything seems to work as expected.
