### ISSUE TITLE
Follow semantic versioning

### ISSUE THREAD

**Issue by ahmetb** [coreos/zetcd#60]
Per http://semver.org/, I suggest adopting MAJOR.MINOR.PATCH versioning for tagging releases.

Version numbers like 0.0.1 and 0.0.2 do not tell anything useful and easily parsable to users.

However 0.1.0 tells that it's a pre-stable release, and 0.2.0 is new features added to it, but still pre-release. 0.2.1 would mean it's a bugfix release etc.

**Comment by xiang90** [comment]
> Major version zero (0.y.z) is for initial development. Anything may change at any time. The public API should not be considered stable.

> Version 1.0.0 defines the public API. The way in which the version number is incremented after this release is dependent on this public API and how it changes.

> How should I deal with revisions in the 0.y.z initial development phase?

> The simplest thing to do is start your initial development release at 0.1.0 and then increment the > minor version for each subsequent release.

There is nothing we will commit to before 1.0.0. And it does not violate semver. I would rather close this issue for now.
